package com.example.ui

object Localization {
    val languages = listOf(
        "en" to "English (US) 🇺🇸",
        "fr" to "Français 🇫🇷",
        "es" to "Español 🇪🇸",
        "de" to "Deutsch 🇩🇪"
    )

    private val translations = mapOf(
        "en" to mapOf(
            "meters" to "Meters",
            "profile" to "Profile Settings",
            "app_title" to "H2O Hydration Tracker",
            "app_subtitle" to "Smart metabolic hydration metrics",
            "reset_all" to "Reset Today",
            "clear_all" to "Are you sure you want to delete all historical logs? This cannot be undone.",
            "total_intake" to "Total Intake",
            "daily_goal" to "Daily Goal",
            "remaining" to "Remaining",
            "complete" to "Complete!",
            "quick_add" to "Quick Hydrate",
            "custom_amount" to "Custom Drink (ml)",
            "add_custom" to "Log Custom Intake",
            "weekly_progress" to "Weekly Progress (Last 7 Days)",
            "history_chart_title" to "7-Day Intake Progress",
            "today_logs" to "Today's Drink History Records",
            "no_logs_today" to "No water logged yet for today. Stay hydrated!",
            "google_linked" to "Linked Google Account Active",
            "google_logout" to "Logged out of your Google account",
            "settings" to "Physical Profile Settings",
            "age" to "Age (years)",
            "gender" to "Gender",
            "height" to "Height (cm)",
            "weight" to "Weight (kg)",
            "activity" to "Daily Activity Level",
            "climate" to "Regional Climate Profile",
            "wake" to "Wake Time",
            "sleep" to "Sleep Time",
            "reminders" to "Active Direct Notification Alarms",
            "reminder_interval" to "Reminder Intermission Check (Minutes)",
            "save_confirm" to "Calculated profiles updated automatically!",
            "google_analytics" to "Google Analytics Telemetry",
            "google_analytics_desc" to "Real-time Google Analytics streaming. Connected to trace live active usage, device metrics, and retention events globally.",
            "opt_in_analytics" to "Enable Google Analytics Sharing",
            "mock_dashboard_title" to "Live Analytics & Telemetry Dashboard",
            "active_users" to "Live Active Users (App-wide)",
            "events_tracked" to "Events Fired (This Session)",
            "device_info" to "Client Device Info Logged",
            "test_event" to "Trigger Custom SDK Heartbeat Event",
            "test_event_logged" to "Analytics event 'heartbeat_ping' dispatched successfully!",
            "autosave_prompt" to "Auto-saving calculated profile...",
            "last_logs" to "Real-time user demographic diagnostics",
            "choose_lang" to "Select App Interface Language",
            "gender_male" to "Male",
            "gender_female" to "Female",
            "gender_other" to "Other",
            "climate_normal" to "Normal",
            "climate_hot" to "Hot/Tropical",
            "climate_cold" to "Cold",
            "activity_sedentary" to "Sedentary",
            "activity_active" to "Active",
            "activity_highly" to "Highly Active",
            "security_shield" to "Security & Anti-Tampering Shield",
            "pin_enabled" to "Enable App Lock PIN Protection",
            "enter_pin" to "Enter 4-Digit Security PIN",
            "biometric_auth" to "Enable Biometric Authentication (FaceID/Fingerprint)",
            "db_encryption" to "AES-256 Room DB Cryptographic Storage",
            "db_encrypted" to "Airtight secure cryptographic keys auto-managed by Android Keystore.",
            "lock_now" to "Lock app immediately",
            "enter_pin_to_unlock" to "Enter your secure app lock PIN to open H2O",
            "wrong_pin" to "Incorrect Security PIN. Please try again.",
            "unlocked" to "App lock authenticated successfully!"
        ),
        "fr" to mapOf(
            "meters" to "Suivi",
            "profile" to "Mon Profil",
            "app_title" to "H2O Suivi Hydratation",
            "app_subtitle" to "Données intelligentes de métabolisme",
            "reset_all" to "Réinitialiser",
            "clear_all" to "Êtes-vous sûr de vouloir supprimer tout l'historique ? Cette action est irréversible.",
            "total_intake" to "Consommé",
            "daily_goal" to "Objectif Quotidien",
            "remaining" to "Restant",
            "complete" to "Complété !",
            "quick_add" to "Hydratation Rapide",
            "custom_amount" to "Boisson personnalisée (ml)",
            "add_custom" to "Enregistrer la boisson",
            "weekly_progress" to "Progression hebdomadaire (7 derniers jours)",
            "history_chart_title" to "Progression de l'hydratation (7j)",
            "today_logs" to "Historique des boissons d'aujourd'hui",
            "no_logs_today" to "Aucun enregistrement pour aujourd'hui. Hydratez-vous !",
            "google_linked" to "Compte Google Actif Associé",
            "google_logout" to "Déconnecté de votre compte Google",
            "settings" to "Paramètres du Profil Physique",
            "age" to "Âge (années)",
            "gender" to "Genre",
            "height" to "Taille (cm)",
            "weight" to "Poids (kg)",
            "activity" to "Niveau d'activité physique",
            "climate" to "Climat régional",
            "wake" to "Heure de réveil",
            "sleep" to "Heure de coucher",
            "reminders" to "Alarmes de rappel par notification",
            "reminder_interval" to "Intervalle de rappel (Minutes)",
            "save_confirm" to "Profils mis à jour automatiquement !",
            "google_analytics" to "Télémétrie Google Analytics",
            "google_analytics_desc" to "Flux Google Analytics en temps réel. Connecté pour suivre l'utilisation active, l'appareil et la fidélisation globale.",
            "opt_in_analytics" to "Partager les données d'utilisation",
            "mock_dashboard_title" to "Tableau de Bord de Télémétrie Live",
            "active_users" to "Utilisateurs Actifs sur l'App",
            "events_tracked" to "Événements émis (Cette Session)",
            "device_info" to "Infos Appareil Client Loggées",
            "test_event" to "Émettre un battement de coeur (Heartbeat Event)",
            "test_event_logged" to "Événement 'heartbeat_ping' émis pour Google Analytics !",
            "autosave_prompt" to "Auto-sauvegarde du profil...",
            "last_logs" to "Données démographiques en direct",
            "choose_lang" to "Drapeau d'affichage & Langue de l'app",
            "gender_male" to "Homme",
            "gender_female" to "Femme",
            "gender_other" to "Autre",
            "climate_normal" to "Tempéré (Normal)",
            "climate_hot" to "Tropical (Chaud)",
            "climate_cold" to "Polaire (Froid)",
            "activity_sedentary" to "Sédentaire",
            "activity_active" to "Actif",
            "activity_highly" to "Três Actif",
            "security_shield" to "Sécurité & Cryptage Antiphishing",
            "pin_enabled" to "Activer la protection PIN de l'application",
            "enter_pin" to "Saisir le code PIN de sécurité (4 chiffres)",
            "biometric_auth" to "Activer l'empreinte digitale / FaceID",
            "db_encryption" to "Cryptage Room DB AES-256",
            "db_encrypted" to "Données sécurisées par les clés système Android Keystore.",
            "lock_now" to "Verrouiller l'application immédiatement",
            "enter_pin_to_unlock" to "Saisissez votre code PIN pour déverrouiller H2O",
            "wrong_pin" to "Code PIN incorrect. Veuillez réessayer.",
            "unlocked" to "Application déverrouillée avec succès !"
        ),
        "es" to mapOf(
            "meters" to "Medidas",
            "profile" to "Perfil",
            "app_title" to "H2O Rastreador de Agua",
            "app_subtitle" to "Métricas de absorción metabólica",
            "reset_all" to "Reiniciar Hoy",
            "clear_all" to "¿Está seguro de que desea eliminar todo el historial? Esto no se puede deshacer.",
            "total_intake" to "Consumo Total",
            "daily_goal" to "Meta Diaria",
            "remaining" to "Restante",
            "complete" to "¡Completado!",
            "quick_add" to "Hidrato Rápido",
            "custom_amount" to "Bebida personalizada (ml)",
            "add_custom" to "Registrar volumen",
            "weekly_progress" to "Progreso semanal (Últimos 7 días)",
            "history_chart_title" to "Progreso de hidratación de 7 días",
            "today_logs" to "Historial de bebidas de hoy",
            "no_logs_today" to "Aún no hay registros de agua para hoy. ¡Mantente hidratado!",
            "google_linked" to "Cuenta de Google Activa Vinculada",
            "google_logout" to "Sesión de Google cerrada",
            "settings" to "Ajustes del Perfil Físico",
            "age" to "Edad (años)",
            "gender" to "Género",
            "height" to "Altura (cm)",
            "weight" to "Peso (kg)",
            "activity" to "Nivel de actividad diaria",
            "climate" to "Clima Regional",
            "wake" to "Hora de despertar",
            "sleep" to "Hora de dormir",
            "reminders" to "Alarmas de Notificación Directas",
            "reminder_interval" to "Intervalo de Recordatorio (Minutos)",
            "save_confirm" to "¡Perfil actualizado guardado automáticamente!",
            "google_analytics" to "Telemetría Google Analytics",
            "google_analytics_desc" to "Tráfico en tiempo real de Google Analytics. Permite analizar el uso activo de apps, datos geográficos y rendimiento general.",
            "opt_in_analytics" to "Permitir envío a Google Analytics",
            "mock_dashboard_title" to "Panel de Control de Telemetría Live",
            "active_users" to "Usuarios Activos Mundiales",
            "events_tracked" to "Eventos Transmitidos (Sesión)",
            "device_info" to "Info de Dispositivo Registrada",
            "test_event" to "Lanzar Evento de Control (Heartbeat Ping)",
            "test_event_logged" to "¡Evento 'heartbeat_ping' enviado a Google Analytics!",
            "autosave_prompt" to "Auto-guardando configuración...",
            "last_logs" to "Diagnósticos demográficos activos",
            "choose_lang" to "Seleccionar Idioma de Interfaz",
            "gender_male" to "Hombre",
            "gender_female" to "Mujer",
            "gender_other" to "Otro",
            "climate_normal" to "Normal",
            "climate_hot" to "Cálido/Tropical",
            "climate_cold" to "Frío",
            "security_shield" to "Seguridad y Escudo de Privacidad",
            "pin_enabled" to "Activar protección PIN para de la aplicación",
            "enter_pin" to "Introducir PIN de seguridad (4 dígitos)",
            "biometric_auth" to "Habilitar autenticidad biométrica (FaceID/Huella)",
            "db_encryption" to "Cifrado de base de datos AES-256 Room",
            "db_encrypted" to "Datos protegidos por claves del sistema Android Keystore.",
            "lock_now" to "Bloquear aplicación de inmediato",
            "enter_pin_to_unlock" to "Introduzca su PIN para desbloquear H2O",
            "wrong_pin" to "PIN de seguridad incorrecto. Inténtelo de nuevo.",
            "unlocked" to "¡Aplicación desbloqueada con éxito!"
        ),
        "de" to mapOf(
            "meters" to "Messwerte",
            "profile" to "Profil",
            "app_title" to "H2O Trinkerinnerung",
            "app_subtitle" to "Intelligente metabolische Analyse",
            "reset_all" to "Zurücksetzen",
            "clear_all" to "Möchten Sie den gesamten Verlauf wirklich unwiderruflich löschen?",
            "total_intake" to "Gesamtverbrauch",
            "daily_goal" to "Tagesziel",
            "remaining" to "Verbleibend",
            "complete" to "Vollendet!",
            "quick_add" to "Schnell Trinken",
            "custom_amount" to "Gewähltes Getränk (ml)",
            "add_custom" to "Hinzufügen",
            "weekly_progress" to "Fortschritt der letzten 7 Tage",
            "history_chart_title" to "7-Tage-Historie",
            "today_logs" to "Heutige Trink-Historie",
            "no_logs_today" to "Heute noch nichts getrunken. Bleib hydriert!",
            "google_linked" to "Google-Anmeldung aktiv",
            "google_logout" to "Vom Google-Konto abgemeldet",
            "settings" to "Körperliche Profileinstellungen",
            "age" to "Alter",
            "gender" to "Geschlecht",
            "height" to "Größe (cm)",
            "weight" to "Gewicht (kg)",
            "activity" to "Aktivitätsgrad",
            "climate" to "Regionales Klima",
            "wake" to "Weckzeit",
            "sleep" to "Schlafenszeit",
            "reminders" to "Aktive Trinkerinnerungen",
            "reminder_interval" to "Intervall (Minuten)",
            "save_confirm" to "Profil automatisch synchronisiert!",
            "google_analytics" to "Google Analytics-Überwachung",
            "google_analytics_desc" to "Interaktives Google Analytics Streaming. Zeigt globale Demografie, Echtzeitabfragen und Event-Tracking.",
            "opt_in_analytics" to "Google Analytics Verfolgung erlauben",
            "mock_dashboard_title" to "Live Analytics & Telemetriebildschirm",
            "active_users" to "Aktive Benutzer weltweit",
            "events_tracked" to "Echtzeit-Sitzungsereignisse",
            "device_info" to "Gerätediagnostik",
            "test_event" to "Test-Ereignis senden (Heartbeat)",
            "test_event_logged" to "Ereignis 'heartbeat_ping' wurde an Google Analytics gesendet!",
            "autosave_prompt" to "Profildaten automatisch gesichert...",
            "last_logs" to "Benutzerstatistik",
            "choose_lang" to "Interface-Sprache anpassen",
            "gender_male" to "Männlich",
            "gender_female" to "Weiblich",
            "gender_other" to "Andere",
            "climate_normal" to "Normal",
            "climate_hot" to "Heiß/Tropisch",
            "climate_cold" to "Kalt",
            "security_shield" to "Datenschutz- & Anti-Manipulationsschutz",
            "pin_enabled" to "App-Sperre aktivieren (PIN)",
            "enter_pin" to "Sicherheits-PIN eingeben (4-stellig)",
            "biometric_auth" to "Biometrische Authentifizierung aktivieren (FaceID/Fingerabdruck)",
            "db_encryption" to "AES-256 Room DB-Verschlüsselung",
            "db_encrypted" to "Sicherheitsdaten geschützt durch das Android Keystore System.",
            "lock_now" to "App sofort sperren",
            "enter_pin_to_unlock" to "Sicherheits-PIN eingeben, um H2O zu öffnen",
            "wrong_pin" to "Falsche Sicherheits-PIN. Bitte versuchen Sie es erneut.",
            "unlocked" to "Erfolgreich entsperrt!"
        )
    )

    fun get(key: String, lang: String): String {
        val langMap = translations[lang] ?: translations["en"]!!
        return langMap[key] ?: key
    }
}
